POST http://localhost:3003/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhdWxkYXVsIiwiaWQiOiI2ODhhNzg5ZjRjMzE5NmQ2NmQwMWFlMjEiLCJpYXQiOjE3NTM5MDU0MzUsImV4cCI6MTc1MzkwOTAzNX0.J-P7YDee2WKIWYeWKFGtbKqHxCvEmPoTX4raYRHrAaI
Content-Type: application/json

{
  "title": "daul's blddsog",
  "author": "John Doe",
  "url": "http://example.com",
  "likes": 12
} 

// REST is not working sometimes - gotta reload vscode once in a while. Curl always works for me